[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "uv run granian --host 0.0.0.0 --port ${PORT:-8000} --interface asgi --access-log --log-level info src.ai_classifier.main:app"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

